openapi: 3.0.2
info:
  title: Book API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: development
paths:
  /books:
    get:
      description: Show my book list
      operationId: getBooks
      responses:
        '200':
          $ref: '#/components/responses/Books'
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          example: 01
        title:
          type: string
          example: Teresa book
        author:
          type: string
          example: Teresa
        finished_at:
          type: string
          format: date
          example: '2015-05-05'
      required:
        - id
        - title
        - author
    Books:
      type: object
      properties:
        books:
          type: array
          items:
            $ref: '#/components/schemas/Book'
      required:
        - books
  responses:
    Books:
      description: Array of books
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Books'
