/*
 * Book API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Book struct {

	Id int32 `json:"id"`

	Title string `json:"title"`

	Author string `json:"author"`

	FinishedAt string `json:"finished_at,omitempty"`
}
